-- Crear tabla para transacciones financieras
create table public.transacciones (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  descripcion text not null,
  monto decimal(12,2) not null,
  tipo text check (tipo in ('ingreso', 'gasto')) not null,
  categoria text,
  estado text check (estado in ('completado', 'pendiente', 'procesado')) default 'pendiente',
  fecha date default current_date
);

-- Configurar Row Level Security (RLS)
alter table public.transacciones enable row level security;

create policy "Permitir lectura para todos"
on public.transacciones for select
using (true);

create policy "Permitir inserción para todos"
on public.transacciones for insert
with check (true);

-- Crear tabla para cotizaciones
create table public.cotizaciones (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  cliente_nombre text not null,
  cliente_email text,
  proyecto_nombre text not null,
  estado text check (estado in ('borrador', 'enviada', 'aceptada', 'rechazada')) default 'borrador',
  monto_total decimal(12,2) default 0,
  valido_hasta date
);

-- Crear tabla para items de cotización
create table public.items_cotizacion (
  id bigint generated by default as identity primary key,
  cotizacion_id bigint references public.cotizaciones(id) on delete cascade not null,
  descripcion text not null,
  cantidad decimal(10,2) not null,
  precio_unitario decimal(12,2) not null,
  total decimal(12,2) generated always as (cantidad * precio_unitario) stored
);

-- RLS para cotizaciones
alter table public.cotizaciones enable row level security;

create policy "Permitir lectura para todos" on public.cotizaciones for select using (true);
create policy "Permitir inserción para todos" on public.cotizaciones for insert with check (true);

-- RLS para items_cotizacion
alter table public.items_cotizacion enable row level security;

create policy "Permitir lectura para todos" on public.items_cotizacion for select using (true);
create policy "Permitir inserción para todos" on public.items_cotizacion for insert with check (true);
