-- Crear tabla para facturas
create table if not exists public.facturas (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tipo text check (tipo in ('compra', 'venta')) not null,
  numero_factura text not null,
  fecha_emision date not null,
  entidad text not null, -- Cliente para venta, Proveedor para compra
  descripcion text,
  servicio text, -- Solo requerido para facturas de compra
  monto_neto decimal(12,2) not null,
  iva decimal(12,2) not null,
  monto_total decimal(12,2) not null,
  estado text check (estado in ('pagada', 'pendiente', 'anulada')) default 'pendiente'
);

-- Habilitar RLS
alter table public.facturas enable row level security;

-- Políticas de seguridad
create policy "Permitir lectura para autenticados" on public.facturas for select using (auth.role() = 'authenticated');
create policy "Permitir inserción para autenticados" on public.facturas for insert with check (auth.role() = 'authenticated');
create policy "Permitir actualización para autenticados" on public.facturas for update using (auth.role() = 'authenticated');
create policy "Permitir eliminación para autenticados" on public.facturas for delete using (auth.role() = 'authenticated');
