-- Crear tabla para mensajes de contacto
create table if not exists public.mensajes_contacto (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text not null,
  email text not null,
  telefono text,
  asunto text not null,
  mensaje text not null,
  estado text check (estado in ('nuevo', 'leido', 'respondido')) default 'nuevo',
  notas text
);

-- Habilitar RLS
alter table public.mensajes_contacto enable row level security;

-- Políticas: Solo usuarios autenticados pueden ver y gestionar mensajes
create policy "Authenticated users can view all contact messages"
  on public.mensajes_contacto for select
  using (auth.role() = 'authenticated');

create policy "Anyone can insert contact messages"
  on public.mensajes_contacto for insert
  with check (true);

create policy "Authenticated users can update contact messages"
  on public.mensajes_contacto for update
  using (auth.role() = 'authenticated');

create policy "Authenticated users can delete contact messages"
  on public.mensajes_contacto for delete
  using (auth.role() = 'authenticated');
