-- Crear tabla para configuración de la empresa
create table if not exists public.configuracion (
  id bigint generated by default as identity primary key,
  nombre_empresa text default 'Vergara Ingeniería',
  rut text,
  direccion text,
  email_contacto text,
  telefono text,
  moneda text default 'CLP',
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Insertar fila por defecto si no existe
insert into public.configuracion (id, nombre_empresa, rut, direccion, email_contacto, telefono)
select 1, 'Vergara Ingeniería', '76.123.456-K', 'Av. Providencia 1234, Of. 505', 'contacto@vergaraingenieria.cl', '+56 9 1234 5678'
where not exists (select 1 from public.configuracion);

-- RLS para configuración
alter table public.configuracion enable row level security;

create policy "Permitir lectura para todos" on public.configuracion for select using (true);
create policy "Permitir modificación para autenticados" on public.configuracion for update using (auth.role() = 'authenticated');
create policy "Permitir inserción para autenticados" on public.configuracion for insert with check (auth.role() = 'authenticated');
